In [1]:
using LinearAlgebra, Plots, Printf, Latexify, LaTeXStrings, BenchmarkTools, ArnoldiMethod, SparseArrays
using MatrixMarket: mmread

In [2]:
function MGS_arnoldi(A, q1::Vector{Float64}, k::Int)
  n, _ = size(A)
  Q = zeros(Float64, (n, k + 1))
  q = zeros(Float64, n)
  H = zeros(Float64, (k + 1, k))
  w = zeros(Float64,n)
  Q[:, 1] = q1 ./ norm(q1)
  for j in 1:k
    w .= A * Q[:, j]        
    for i in 1:j
      q .= Q[:, i]
      H[i, j] = q'w
      w -= H[i, j] .* q
    end
    H[j + 1, j] = norm(w)
    Q[:, j + 1] = w ./ H[j + 1, j]
  end
  return Q, H
end;

In [3]:
function CGS2_arnoldi(A, q1::Vector{Float64}, k::Int)
  n, _ = size(A)
  Q = zeros(Float64, (n, k + 1))
  H = zeros(Float64, (k + 1, k))
  h = zeros(Float64, k + 1)
  w = zeros(Float64, n)
  Q[:, 1] = q1 ./ norm(q1)
  for j in 1:k
    w .= A * Q[:, j]
    h .= Q'w
    h[j+1:k+1] .= 0.
    H[:, j] = h
    w -= Q * h
    h .= Q'w
    h[j+1:k+1] .= 0.
    w -= Q * h
    H[j + 1, j] = norm(w)
    Q[:, j + 1] = w ./ H[j + 1, j]
  end
  return Q, H
end;

In [4]:
matrix_folder = "/home/venkovic/Dropbox/Git/matrix-market/";
A = mmread(matrix_folder * "G3_circuit.mtx");
n, _ = size(A);

In [5]:
k = 100;

In [6]:
Q, H = @time MGS_arnoldi(A, rand(n), k);
@printf "||Qjp1 * A * Qj - H|| = %.2E, ||A * Qj - Qjp1 * H|| = %.2E, ||I - Q'Q|| = %.2E" norm(Q'A * Q[:, 1:k] - H) norm(A * Q[:, 1:k] - Q * H) norm(I - Q'Q)

 48.308685 seconds (1.03 M allocations: 183.798 GiB, 8.01% gc time, 0.55% compilation time)
||Qjp1 * A * Qj - H|| = 4.26E-07, ||A * Qj - Qjp1 * H|| = 5.52E-11, ||I - Q'Q|| = 2.80E-11

In [7]:
Q, H = @time CGS2_arnoldi(A, rand(n), k);
@printf "||Qjp1 * A * Qj - H|| = %.2E, ||A * Qj - Qjp1 * H|| = %.2E, ||I - Q'Q|| = %.2E" norm(Q'A * Q[:, 1:k] - H) norm(A * Q[:, 1:k] - Q * H) norm(I - Q'Q)

 18.430319 seconds (788.68 k allocations: 9.537 GiB, 3.00% gc time, 1.15% compilation time)
||Qjp1 * A * Qj - H|| = 3.11E-10, ||A * Qj - Qjp1 * H|| = 1.02E-10, ||I - Q'Q|| = 1.58E-14

In [8]:
function RR_CGS2_arnoldi(A, q1::Vector{Float64}, k::Int, nev::Int, tol::Float64)
  n, _ = size(A)
  Q = zeros(Float64, (n, k + 1))
  H = zeros(Float64, (k + 1, k))
  h = zeros(Float64, k + 1)
  w = zeros(Float64, n)
  Q[:, 1] = q1 ./ norm(q1)
  j = 0
  res = 1.; vals = nothing; vecs = nothing; order = nothing
  while (maximum(res) > tol && j < k)
    j += 1
    w .= A * Q[:, j]
    h .= Q'w
    h[j+1:k+1] .= 0.
    H[:, j] = h
    w -= Q * h
    h .= Q'w
    h[j+1:k+1] .= 0.
    w -= Q * h
    H[j + 1, j] = norm(w)
    Q[:, j + 1] = w ./ H[j + 1, j]        
    vals, vecs = eigen(H[1:j, 1:j], sortby=norm)
    order = (j:-1:j-min(nev,j)+1)
    res = norm(H[j + 1, j]) .* norm.(vecs[j, order]) ./ norm.(vals[order])
    println(res)
  end
  return res, vals[order], Q[:, 1:j] * vecs[:, order]
end;

In [9]:
A = mmread(matrix_folder * "nxp1.mtx");
n, _ = size(A);

In [10]:
k = 100;
nev = 5;
tol = 1e-6;
res, vals, Y = RR_CGS2_arnoldi(A, rand(n), k, nev, tol);

[7.077121224720258]
[0.8088325836774486, 8.940819729164783]
[0.42836453484246684, 0.9012139839285507, 8.959983869908008]
[0.23987016702375555, 0.441370493207317, 0.8023386303399367, 7.0810812827339475]
[0.09356188499203713, 0.2605314762175195, 0.6511503134437958, 1.2230183421941068, 8.565952217733294]
[0.09239173884785262, 0.383504975237183, 0.3842832494242673, 0.6693571663094374, 1.6199085694690543]
[0.18654176600241557, 0.13370814969729256, 0.2218924661695702, 0.41322250544888184, 0.5422954265983602]
[0.06649971130021196, 0.037766797288557585, 0.1786827524521659, 0.21589210897536334, 0.39816107105870696]
[0.01408979318973101, 0.010861355293330117, 0.08851329321127348, 0.12515882387725835, 0.26440213360178316]
[0.003921453560715193, 0.00426341033613029, 0.06880911574072213, 0.17693754563503986, 0.2787419156717702]
[0.0007327295977502436, 0.0011391515985940466, 0.04235843540751189, 0.11511092349685859, 0.09256699769342222]
[0.00018156096079676153, 0.0003916154222483927, 0.0296335375456

In [11]:
res2 = [norm(A * Y[:, i] - vals[i] .* Y[:, i]) / norm(vals[i]) for i in 1:nev];
maximum(res - res2)

-3.1028934440293157e-18

In [12]:
decomp, hist = partialschur(A, nev=nev);
vals2, Y2 = partialeigen(decomp);

In [13]:
maximum(abs.(vals2[end:-1:1] .- vals))

1.5225509741867427e-10

In [14]:
norm(abs.(Y'Y2[:, end:-1:1]) - I)

6.52696323254773e-9

In [15]:
vals

5-element Vector{Float64}:
 414.7385747346635
 341.5391676335881
 257.3852366214979
 257.1813229755226
 255.8853137891478

In [16]:
function HR_CGS2_arnoldi(A, q1::Vector{Float64}, k::Int, nev::Int, sigma::ComplexF64, tol::Float64)
  n, _ = size(A)
  Q = zeros(Float64, (n, k + 1))
  H = zeros(Float64, (k + 1, k))
  h = zeros(Float64, k + 1)
  w = zeros(Float64, n)
  Q[:, 1] = q1 ./ norm(q1)
  j = 0
  res = 1.; rho = nothing; vecs = nothing
  while (maximum(res) > tol && j < k)
    j += 1
    w .= A * Q[:, j]
    h .= Q'w
    h[j+1:k+1] .= 0.
    H[:, j] = h
    w -= Q * h
    h .= Q'w
    h[j+1:k+1] .= 0.
    w -= Q * h
    H[j + 1, j] = norm(w)
    Q[:, j + 1] = w ./ H[j + 1, j]
    e_j = zeros(Float64, j); e_j[j] = 1.
    f = (H[1:j, 1:j] - sigma * I)' \ e_j
    G = H[1:j, 1:j] + norm(H[j + 1, j])^2 .* f * e_j'
    vals, vecs = eigen(G)
    order = sortperm(norm.(vals .- sigma))[1:minimum([j, nev])]
    vals = vals[order]
    vecs = vecs[:, order]    
    rho = [vals[i] - norm(H[j + 1, j])^2 * vecs[:, i]'f * vecs[j, i] for i in 1:minimum([j, nev])]
    res = sqrt.(real.((vals .- rho) .* conj.(rho .- sigma)))
    res ./= norm.(rho)
    #hres = (vals .- rho) .* conj.(vals .- sigma)
    println(res)
  end
  return res, rho, Q[:, 1:j] * vecs
end;

In [17]:
k = 500
nev = 2;
sigma = 150. + 0im;
res, vals, Y = HR_CGS2_arnoldi(A, rand(n), k, nev, sigma, tol);

[7.016647270520317]
[0.7537020950746832, 12.48922273396239]
[0.7220549993306318, 10.747941531872511]
[0.56768068665105, 0.30688197082834695]
[0.22668309068555506, 0.473757535264876]
[0.21793380628430079, 0.440935670308563]
[0.18254618641381584, 0.3125317613184449]
[0.16178995778117514, 0.30285794276575717]
[0.09993933671293344, 0.20088595757421515]
[0.09817571327098998, 0.20045432940154514]
[0.0811801535621453, 0.13552653847027377]
[0.07607796277738636, 0.1385279847415917]
[0.06518062222853496, 0.0963034552993034]
[0.054184595479828325, 0.10193279162865491]
[0.05531792151104602, 0.08008773059214988]
[0.04187270670580756, 0.08885546921355564]
[0.04040832837578404, 0.09143184887379215]
[0.052251160763928745, 0.08551482957777856]
[0.04865451505804748, 0.0959688398738821]
[0.05636611085891781, 0.09207511559246723]
[0.053691709710036326, 0.09706546092976016]
[0.061934416509189676, 0.09437935547554684]
[0.06153998836535882, 0.08548154964884458]
[0.06156488942609437, 0.08402917312703266]
[0.0

[0.000845268109286723, 0.0011442978823765712]
[0.0006863643606106584, 0.0009002202674035343]
[0.0006707920063203199, 0.0008765636513209759]
[0.0006047087717252271, 0.0007826304239669118]
[0.00044552084369914476, 0.0005623031363827944]
[0.00030691133022252135, 0.00037934606797488215]
[0.00021866647046648536, 0.0002664479657913242]
[0.00019631965514208742, 0.0002378235223828245]
[0.00019126791394316207, 0.00023213685321771857]
[0.00013616195936668916, 0.0001648135278664741]
[7.319986316349518e-5, 8.79212181353389e-5]
[3.5267375649242886e-5, 4.206823026217109e-5]
[1.9372804169969534e-5, 2.2979312673282612e-5]
[1.4320311296550444e-5, 1.690091712723495e-5]
[1.3881997631280876e-5, 1.634637170627202e-5]
[1.3095214475990093e-5, 1.5481342230291845e-5]
[1.0653234154437074e-5, 1.2591015377486179e-5]
[8.350540519382658e-6, 9.80469600479517e-6]
[6.098891497089153e-6, 7.078691068357962e-6]
[3.7959130676444163e-6, 4.341773555495751e-6]
[1.9847278445331404e-6, 2.242616705671383e-6]
[1.076737333355648e

In [18]:
res2 = [norm(A * Y[:, i] - vals[i] .* Y[:, i]) / norm(vals[i]) for i in 1:nev];
maximum(res - res2)

4.4850087105331173e-13

In [19]:
vals

2-element Vector{ComplexF64}:
 151.0742742327672 - 1.0358806223542427e-14im
 151.3772853007068 - 1.8307032691510355e-14im

In [20]:
res

2-element Vector{Float64}:
 6.795970054094525e-7
 7.570183762896598e-7

In [21]:
function lanczos(A, q1::Vector{Float64}, k::Int)
  n, _ = size(A)
  Q = zeros(Float64, (n, k + 1))
  v = zeros(Float64, n)
  T = zeros(Float64, k + 1, k + 1)
  Q[:, 1] = q1 ./ norm(q1)
  for j in 1:k
    v = A * Q[:, j]
    T[j, j] = Q[:, j]'v
    v = v - T[j, j] * Q[:, j]
    if (j > 1)
      v -= T[j, j - 1] * Q[:, j - 1]
    end
    T[j + 1, j] = norm(v); T[j, j + 1] = T[j + 1, j]
    Q[:, j + 1] = v ./ T[j + 1, j]
  end
  return Q, T[1:k+1, 1:k]
end;

In [22]:
A = mmread(matrix_folder * "Kuu.mtx");
n, _ = size(A);

In [23]:
k = 100;

In [24]:
Q, T = @time lanczos(A, rand(n), k);
@printf "||Qjp1 * A * Qj - T|| = %.2E, ||A * Qj - Qjp1 * T|| = %.2E, ||I - Q'Q|| = %.2E" norm(Q'A * Q[:, 1:k] - T) norm(A * Q[:, 1:k] - Q * T) norm(I - Q'Q)

  0.297058 seconds (354.62 k allocations: 77.592 MiB, 11.81% gc time, 81.45% compilation time)
||Qjp1 * A * Qj - T|| = 5.31E-09, ||A * Qj - Qjp1 * T|| = 2.04E-14, ||I - Q'Q|| = 1.11E-10

In [37]:
function RR_lanczos(A, q1::Vector{Float64}, k::Int, nev::Int, tol::Float64)
  n, _ = size(A)
  Q = zeros(Float64, (n, k + 1))
  v = zeros(Float64, n)
  T = zeros(Float64, k + 1, k + 1)
  vals = zeros(Float64, nev, k)
  Q[:, 1] = q1 ./ norm(q1)
  j = 0
  res = 1.; vecs = nothing; order = nothing
  while (maximum(res) > tol && j < k)
    j += 1
    v = A * Q[:, j]
    T[j, j] = Q[:, j]'v
    v = v - T[j, j] * Q[:, j]
    if (j > 1)
      v -= T[j, j - 1] * Q[:, j - 1]
    end
    T[j + 1, j] = norm(v); T[j, j + 1] = T[j + 1, j]
    Q[:, j + 1] = v ./ T[j + 1, j]
    _vals, vecs = eigen(T[1:j, 1:j], sortby=norm)
    order = (j:-1:j-min(nev,j)+1)
    vals[1:minimum([j, nev]), j] = _vals[order]
    res = norm(T[j + 1, j]) .* norm.(vecs[j, order]) ./ norm.(_vals[order])
    println(res)
  end
  return res, vals[:, 1:j], Q[:, 1:j] * vecs[:, order]
end;

In [38]:
k = 500;
nev = 5;
res, vals, Y = RR_lanczos(A, rand(n), k, nev, tol);

[2.468130045237282]
[0.4223110696508644, 3.7699398494239547]
[0.24714247161508776, 0.5746526104430993, 5.067335659331438]
[0.1282917102744072, 0.2583301985514785, 0.572296557663772, 5.836510264705831]
[0.061713959758911176, 0.18416775399626173, 0.4238275564358927, 0.7537795050581154, 7.721825485223366]
[0.060547288111776065, 0.2444407623027702, 0.2453917031822459, 0.38781360504126267, 0.7139076404766664]
[0.042563767919939724, 0.10540575912860681, 0.10998012730511489, 0.2866486188352748, 0.4776559423466383]
[0.03632472309041815, 0.08542136305132364, 0.22274630795154296, 0.2963558233744388, 0.3042200474733747]
[0.03669299978572112, 0.08466452949179688, 0.17478113219527916, 0.10314884236011686, 0.275821414169738]
[0.03718600688951825, 0.06975356227230674, 0.09963539729631647, 0.13375503896026536, 0.23837772712438735]
[0.025072277952943613, 0.04035364273710121, 0.058687198476261894, 0.1485772628888903, 0.11386536098978386]
[0.026894141578478224, 0.04376624275742907, 0.08423298853109472, 0

[1.623676205929599e-6, 3.153989792781016e-5, 0.0002052502542774325, 0.0016777387888880222, 0.002942756868916081]
[1.4009375084540149e-6, 2.800798482698533e-5, 0.00019333981682030215, 0.001636363862529526, 0.002955779730075668]
[9.144411043370046e-7, 1.8624096386059144e-5, 0.0001336036862299003, 0.001157976765054403, 0.002139163315486561]
[8.540428884247615e-7, 1.771193008030738e-5, 0.00013176827456784545, 0.0011686273115854798, 0.0022122202064349806]
[7.146644687722783e-7, 1.5157581979799673e-5, 0.00011796468672800999, 0.0010773659245687248, 0.0021092256023526428]
[5.187520265489222e-7, 1.1218185071008589e-5, 9.078673022504685e-5, 0.0008510935664087919, 0.0017200158615595358]
[4.2929386883004353e-7, 9.435587563023628e-6, 7.884548368159321e-5, 0.0007551999628883345, 0.0015684488627477752]
[4.164422111449035e-7, 9.36958696369842e-6, 8.197294031459422e-5, 0.0008100382514642814, 0.0017533024313853044]
[2.585333573482631e-7, 5.936317651288746e-6, 5.4087658774345986e-5, 0.0005498579761639056

In [39]:
res2 = [norm(A * Y[:, i] - vals[i, end] .* Y[:, i]) / norm(vals[i, end]) for i in 1:nev];
maximum(res - res2)

1.104552139043289e-17

In [41]:
vals[:, end]

5-element Vector{Float64}:
 54.08205599641253
 53.98165804506267
 53.815496452830125
 53.720402051506035
 53.62254145454774